apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.api.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.api.name }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.api.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.api.name }}
    spec:
      containers:
      - name: {{ .Values.api.name }}
        image: markusryoti/detect-rs
        imagePullPolicy: Always # dev
        ports:
        - containerPort: 8080
        env:
        - name: RUST_LOG
          value: info
        env:
        - name: OTEL_ADDR
          value: "http://{{ .Values.otel.serviceName }}.{{ .Values.otel.namespace }}.svc.cluster.local:4318/v1/traces"

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.api.name }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
