apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.web.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.web.name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.web.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.web.name }}
    spec:
      containers:
      - name: {{ .Values.web.name }}
        image: markusryoti/detect-web
        imagePullPolicy: Always # dev
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.web.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.web.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
