mode: "deployment"

config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: ${env:MY_POD_IP}:4317
        http:
          endpoint: ${env:MY_POD_IP}:4318

  exporters:
    otlp: 
      endpoint: jaeger-collector:4317
      tls:
        insecure: true

  service:
    pipelines:
      traces:
        exporters:
          - otlp
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp

