allInOne:
  enabled: true

provisionDataStore:
  cassandra: false

storage:
  type: memory

agent:
  enabled: false

collector:
  enabled: false

query:
  enabled: false

service:
  type: ClusterIP

# collector:
#   enabled: true
#   service:
#     otlp:
#       enabled: true
#       grpc:
#         name: otlp-grpc
#         port: 4317
#       http:
#         name: otlp-http
#         port: 4318
